# Generated by Django 2.2.7 on 2019-12-02 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20191202_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='country',
            field=models.Field(max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=32),
        ),
    ]
