# Generated by Django 2.2.7 on 2019-12-02 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20191202_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='country',
            field=models.CharField(max_length=30),
        ),
    ]
